<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript', 
    array('conditional' => 'lt IE9',));

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('SpeckCommerce') ?>

    <?php echo $this->headMeta() ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>">SpeckCommerce</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
            </ul>
          <?php if ($this->zfcUserIdentity()): ?>
              <ul class="nav secondary-nav pull-right">
                <li><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 25), array('style' => 'padding-top: 8px;')) ?></li>
                <li><a href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->zfcUserIdentity()->getDisplayName() ?></a></li>
                <li><a href="<?php echo $this->url('zfcuser/logout') ?>">Sign Out</a></li>
              </ul>
          <?php else: ?>
              <form action="<?php echo $this->url('zfcuser/login') ?>" method="post" class="small-login-form form-inline pull-right">
                <input name="identity" class="input-small" type="text" placeholder="Username">
                <input name="credential" class="input-small" type="password" placeholder="Password">
                <button class="btn" type="submit">Sign in</button>
                <?php echo $this->formCsrf('csrf') ?>
              </form>
          <?php endif; ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>Powered by <a href="http://speckcommerce.com/">SpeckCommerce</a>.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
