<?php
echo $this->doctype();
?>

<html lang="en">
    <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php
        echo $this->headlink();
        echo $this->headStyle();
        echo $this->headScript();
    ?>
    </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="<?php echo $this->url('home') ?>">SpeckCommerce</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
              </ul>
          <?php if ($this->zfcUserIdentity()): ?>
            <ul class="nav secondary-nav pull-right">
                <li class="dropdown" id="account_menu" >
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#account_menu"><?php echo $this->zfcUserDisplayName() . $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 16), array('style' => 'vertical-align:middle;padding-left:8px;')) ?></a>
                    <ul class="dropdown-menu" style="padding-left:72px;padding-right:4px;height:auto !important;height:66px;min-height:66px;">
                        <li>
                            <div style="position:absolute;left:4px;top:4px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 64), array('style' => '')) ?></div>
                            <a href="<?php echo $this->url('zfcuser') ?>"><i class="icon-user"></i> Account Information</a>
                        </li>
                        <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><i class="icon-off"></i> Sign Out</a></li>
                    </ul>
                </li>
            </ul>
          <?php else: ?>
              <form action="<?php echo $this->url('zfcuser/login') ?>" method="post" class="small-login-form form-inline pull-right">
                <input name="identity" class="input-small" type="text" placeholder="Username">
                <input name="credential" class="input-small" type="password" placeholder="Password">
                <?php
                    $loginForm = $this->zfcUserLoginWidget(array('render' => false))->loginForm;
                    // I didn't really find a better way of doing this...
                if (isset($_GET['redirect'])): ?>
                    <input type="hidden" name="redirect" value="<?php echo $_GET['redirect']; ?>" />
                <?php else: ?>
                    <input type="hidden" name="redirect" value="<?php echo $_SERVER['REQUEST_URI']; ?>" />
                <?php endif; ?>
                <button class="btn btn-small" type="submit"><i class="icon-ok"></i> Sign in</button>
              </form>
          <?php endif; ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>Powered by <a href="http://speckcommerce.org/">SpeckCommerce</a>.</p>
        <p>Icons provided by <a title="GLYPHICONS is a library of precisely prepared monochromatic icons and symbols, created with an emphasis on simplicity and easy orientation." href="http://www.glyphicons.com/">glyphicons.com</a></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
