<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()
    //prepend , load in reverse
    ->prependFile($basePath . '/js/bootstrap-dropdown.js', 'text/javascript')
    ->prependFile($basePath . '/js/bootstrap-modal.js', 'text/javascript')
    ->prependFile($basePath . '/js/bootstrap-tab.js', 'text/javascript')
    ->prependFile($basePath . '/js/jquery-ui-1.8.18.js', 'text/javascript')
    ->prependFile($basePath . '/js/jquery-1.7.2.min.js', 'text/javascript')
    ->prependFile($basePath . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE9',)
);

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('SpeckCommerce') ?>

    <?php echo $this->headMeta() ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>">SpeckCommerce</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
            </ul>
          <?php if ($this->zfcUserIdentity()): /* echo $this->url('zfcuser') */ ?>
            <ul class="nav secondary-nav pull-right">
                <li class="dropdown" id="account_menu" >
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#account_menu"><?php echo $this->zfcUserIdentity()->getDisplayName() . $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 16), array('style' => 'vertical-align:middle;padding-left:8px;')) ?></a>
                    <ul class="dropdown-menu" style="padding-left:72px;padding-right:4px;height:auto !important;height:66px;min-height:66px;">
                        <li>
                            <div style="position:absolute;left:4px;top:4px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 64), array('style' => '')) ?></div>
                            <a href="<?php echo $this->url('zfcuser') ?>"><i class="icon-user"></i> Account Information</a>
                        </li>
                        <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><i class="icon-off"></i> Sign Out</a></li>
                    </ul>
                </li>
            </ul>
          <?php else: ?>
              <form action="<?php echo $this->url('zfcuser/login') ?>" method="post" class="small-login-form form-inline pull-right">
                <input name="identity" class="input-small" type="text" placeholder="Username">
                <input name="credential" class="input-small" type="password" placeholder="Password">
                <?php 
                    $loginForm = $this->zfcUserLoginWidget(array('render' => false))->loginForm;
                    echo $this->formInput($loginForm->get('csrf'));
                    // I didn't really find a better way of doing this...
                    if (isset($_GET['redirect'])): ?>
                    <input type="hidden" name="redirect" value="<?php echo $_GET['redirect']; ?>" />
                <?php endif; ?>
                <button class="btn btn-small" type="submit"><i class="icon-ok"></i> Sign in</button>
              </form>
          <?php endif; ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>Powered by <a href="http://speckcommerce.com/">SpeckCommerce</a>.</p>
        <p>Icons provided by <a title="GLYPHICONS is a library of precisely prepared monochromatic icons and symbols, created with an emphasis on simplicity and easy orientation." href="http://www.glyphicons.com/">glyphicons.com</a></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
