  <div class="hero-unit">
    <h1>Welcome to SpeckCommerce</h1>
    <p>Congratulations! You have successfully installed <a href="http://speckcommerce.com/">SpeckCommerce</a>. There is not much here yet, so we can use all the development help we can get! You are currently using Zend Framework version <?php echo \Zend\Version\Version::VERSION ?>.</p>
    <p><a class="btn btn-primary btn-large" href="https://github.com/speckcommerce/speck">Fork SpeckCommerce on GitHub &raquo;</a></p>
  </div>

  <div class="row">
    <div class="span4">
      <h2>Built on Zend Framework 2</h2>
        <p>Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework webiste which provides links to the ZF2 <a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">wiki</a>, <a href="http://framework.zend.com/zf2/blog">dev blog</a>, <a href="http://framework.zend.com/issues/browse/ZF2">issue tracker</a>, and much more. This is a great resource for staying up to date with the latest developments!</p>
      <p><a class="btn btn-primary" href="http://framework.zend.com/zf2">ZF2 Development Portal &raquo;</a></p>

    </div>
    <div class="span4">
      <h2>Discover Modules</h2>
       <p>SpeckCommerce is built on ZF2 which has a rapidly growing collection of community-developed modules. The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The site is currently live and currently contains a list of some of the modules already available for ZF2. Any ZF2 module can be installed in SpeckCommerce.</p>
      <p><a class="btn btn-primary" href="http://modules.zendframework.com/">Explore ZF2 Modules &raquo;</a></p>
   </div>
   <div class="span4">

     <h2>Help &amp; Support</h2>
     <p>If you need any help or support with SpeckCommerce, you may reach us via IRC: <a href="irc://irc.freenode.net/speckcommerce">#speckcommerce on Freenode</a>. We'd love to hear any questions or feedback you may have regarding the beta releases..</p>
     <p><a class="btn btn-primary" href="http://webchat.freenode.net?channels=speckcommerce">Ping us on IRC &raquo;</a></p>
   </div>
  </div>
